Eblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
   path('blog/', include('blog.urls')),
]

blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.post_list, name='home'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('category/<int:category_id>/', views.category_list, name='category_list'),    
    # path('tag/<int:tag_id>/', views.tag_list, name='tag_list'),
    path('post/create/', views.create_post, name='create_post'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    # path('post/list/', views.post_list, name='post_list'),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('post/<int:post_id>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/reply/<int:parent_comment_id>/', views.reply_to_comment, name='reply_to_comment'),
    path('api/posts/', views.PostList.as_view(), name='post-list'),
    path('api/posts/<int:post_id>/', views.PostDetail.as_view(), name='post-detail'),
    path('api/posts/<int:post_id>/comments/', views.PostCommentsAPIView.as_view(), name='post-comments-api'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User  
from django.conf import settings


# Define Category Model
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

# Define Tag Model
# class Tag(models.Model):
#     name = models.CharField(max_length=100)

#     def __str__(self):
#         return self.name

# Define Comment Model
# class Comment(models.Model):
#     post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='comments')
#     author = models.ForeignKey(User, on_delete=models.CASCADE)
#     content = models.TextField()
#     created_at = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return f'Comment by {self.author} on {self.post.title}'

# Define Post Model
class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    publication_date = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField(Category, related_name='posts')
    # tags = models.ManyToManyField(Tag, related_name='posts')
    updated_date = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        # Update the updated_date field when saving
        self.updated_date = timezone.now()
        super().save(*args, **kwargs)

# class Post(models.Model):
#     title = models.CharField(max_length=200)
#     content = models.TextField()
#     author = models.ForeignKey(User, on_delete=models.CASCADE)  # If using Django's User model
#     publication_date = models.DateTimeField(auto_now_add=True)
#     # Add more fields as needed
    
#     def __str__(self):
#         return self.title  # Return a human-readable representation of the object

class Comment(models.Model):
    id = models.AutoField(primary_key=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    parent_comment = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.text
    
class CommentReply(models.Model):
    id = models.AutoField(primary_key=True)  # Ensure an AutoField primary key
    text = models.TextField()
    parent_comment = models.ForeignKey('Comment', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # Other fields for your comment reply model

    def __str__(self):
        return self.text

blog/forms.py
# blog/forms.py

from django import forms
from .models import Post
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import Comment, Category, CommentReply


User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

        
class PostForm(forms.ModelForm):
    authors = [(1, 'Author 1'), (2, 'Author 2'), (3, 'Author 3')]  # Replace with your actual author data

    # Create a ChoiceField for the author selection
    author = forms.ChoiceField(choices=authors, required=True)

    class Meta:
        model = Post
        fields = ['title', 'content', 'categories']  # Add fields as needed
    
    # categories = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter categories, separated by commas'}))
    # tags = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter tags, separated by commas'}))

    # def save(self, commit=True):
    #     instance = super().save(commit=False)
    #     categories_input = self.cleaned_data['categories']
    #     tags_input = self.cleaned_data['tags']

    #     if categories_input:
    #         instance.categories.set([category.strip() for category in categories_input.split(',')])
    #     else:
    #         instance.categories.clear()

    #     if tags_input:
    #         instance.tags.set([tag.strip() for tag in tags_input.split(',')])
    #     else:
    #         instance.tags.clear()

    #     if commit:
    #         instance.save()

    #     return instance

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text', 'parent_comment']

        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Write your comment here'}),
        }


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

# class TagForm(forms.ModelForm):
#     class Meta:
#         model = Tag
#         fields = ['name']


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = CommentReply
        fields = ['text', 'parent_comment']  

blog/views.py
import json
from django.shortcuts import render, get_object_or_404,redirect
from .models import Post, Category,Comment
from .forms import PostForm
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.urls import reverse_lazy
from .forms import CustomUserCreationForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from .forms import CommentForm
from rest_framework import generics, status
from .serializers import PostSerializer, CommentSerializer,CategorySerializer
from rest_framework.views import APIView
from rest_framework.response import Response




def post_list(request):
    posts = Post.objects.all()
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comment = Comment.objects.filter(post=post)
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.author = request.user
            if comment_form.cleaned_data['parent_comment']:
                parent_comment = Comment.objects.get(pk=comment_form.cleaned_data['parent_comment'])
                comment.parent_comment = parent_comment
            comment.save()
            return redirect('post_detail', post_id=post.id)
    else:
        comment_form = CommentForm()
    return render(request, 'blog/post_detail.html', {'post': post, 'comments': comment, 'comment_form': comment_form})

def category_list(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    posts = Post.objects.filter(categories=category)
    return render(request, 'blog/category_list.html', {'category': category, 'posts': posts})

# def tag_list(request, tag_id):
#     tag = get_object_or_404(Tag, pk=tag_id)
#     posts = Post.objects.filter(tags=tag)
#     return render(request, 'blog/tag_list.html', {'tag': tag, 'posts': posts})

def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            new_post = form.save()
            categories = Category.objects.all()
            # tags = Tag.objects.all()
            context = {
                'categories': categories,
                # 'tags': tags,
            }
            return redirect('post_detail', post_id=new_post.id)  # Redirect to the newly created post detail page
    else:
        form = PostForm()
    return render(request, 'blog/create_post.html', {'form': form})

class PostDeleteView(DeleteView):
    model = Post
    template_name = 'blog/post_delete.html'  # Create this template
    success_url = reverse_lazy('home')  # Redirect to the post list after deletion


class PostCreateView(CreateView):
    model = Post
    template_name = 'blog/post_form.html'
    form_class = PostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        # Process categories and tags as comma-separated values
        categories = self.request.POST.get('categories', '').split(',')
        # tags = self.request.POST.get('tags', '').split(',')
        
        form.instance.save()
        form.instance.categories.set(Category.objects.filter(name__in=categories))
        # form.instance.tags.set(Tag.objects.filter(name__in=tags))
        return super().form_valid(form)

class PostUpdateView(UpdateView):
    model = Post
    template_name = 'blog/post_form.html'
    form_class = PostForm

    # Update the success_url attribute to use post_id
    def get_success_url(self):
        return reverse_lazy('post_detail', kwargs={'post_id': self.object.id})


class PostUpdateView(UpdateView):
    model = Post
    template_name = 'blog/post_update.html'
    fields = ['title', 'content']
    
    # Update the success_url attribute to use post_id
    def get_success_url(self):
        return reverse_lazy('post_detail', kwargs={'post_id': self.object.id})
    
    def form_valid(self, form):
        # Get selected categories and tags from the form
        categories = self.request.POST.getlist('categories')
        # tags = self.request.POST.getlist('tags')
        
        # Clear existing categories and tags, and associate new ones with the post
        self.object.categories.clear()
        # self.object.tags.clear()
        self.object.categories.add(*categories)
        # self.object.tags.add(*tags)
        
        return super().form_valid(form)
    

def category_list(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    posts = Post.objects.filter(category=category)
    context = {
        'category': category,
        'posts': posts
    }
    return render(request, 'blog/category_list.html', context)

# def tag_list(request, tag_id):
#     tag = get_object_or_404(Tag, pk=tag_id)
#     posts = Post.objects.filter(tags=tag)
#     return render(request, 'blog/tag_list.html', {'tag': tag, 'posts': posts})

# def tag_list(request, tag_id):
#     tag = get_object_or_404(Tag, pk=tag_id)
#     posts = Post.objects.filter(tags=tag)
#     context = {
#         'tag': tag,
#         'posts': posts
#     }
#     return render(request, 'blog/tag_list.html', context)

def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            print("user created")
            return redirect('login')
        else:
            print('user not created')
        
    else:
        print('user not created')
        form = CustomUserCreationForm()
    return render(request, 'blog/register.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            # Redirect to a success page or wherever you want
            return redirect('home')  # Replace 'home' with your URL name
    else:
        # Render the login form
        form = AuthenticationForm()
    return render(request, 'blog/login.html')



from django.http import JsonResponse

def add_comment_to_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    
    if request.method == 'POST':
        if request.content_type == 'application/json':
            # Handle API request
            data = json.loads(request.body.decode('utf-8'))
            comment_form = CommentForm(data)
            
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return JsonResponse({'message': 'Comment added successfully'})
            else:
                return JsonResponse({'errors': comment_form.errors}, status=400)
        else:
            # Handle HTML form submission
            comment_form = CommentForm(request.POST)
            
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect('post_detail', post_id=post.id)
            else:
                print(comment_form.errors)
    else:
        comment_form = CommentForm()
    
    return render(request, 'blog/add_comment_to_post.html', {'form': comment_form})


def reply_to_comment(request, parent_comment_id):
    parent_comment = get_object_or_404(Comment, pk=parent_comment_id)

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = parent_comment.post
            comment.author = request.user
            comment.parent_comment = parent_comment  # Set the parent comment
            comment.save()
            return redirect('post_detail', post_id=parent_comment.post.id)
    else:
        comment_form = CommentForm()

    return render(request, 'blog/reply_to_comment.html', {'parent_comment': parent_comment, 'comment_form': comment_form})



class PostList(generics.ListCreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

class PostDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

class CommentListCreateView(generics.ListCreateAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

class CommentDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

class CategoryListCreateView(generics.ListCreateAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

class CategoryDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


class PostCommentsAPIView(APIView):
    def get(self, request, pk):
        try:
            comments = Comment.objects.filter(post=pk)
            serializer = CommentSerializer(comments, many=True)
            return Response(serializer.data)
        except Comment.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)

blog/templates/blog/add_comment_to_post.html
<!-- blog/add_comment_to_post.html -->
<h2>Add a Comment</h2>
<form method="post">
    {% csrf_token %}
    {{ form.text.label_tag }}
    {{ form.text }}
    <button type="submit">Submit</button>
</form>

<h3>Comments</h3>
{% for comment in comment %}
  <div class="media">
    <img class="rounded-circle article-img" src="{{ comment.author.profile.image.url }}">
    <div class="media-body">
      <h5 class="mt-0">{{ comment.author }}</h5>
      <p>{{ comment.text }}</p>
      <small class="text-muted">{{ comment.created_date|date:"F d, Y H:i" }}</small>
      {% if comment.comment_set.all %}
            <ul>
                {% for reply in comment.comment_set.all %}
                    <li>{{ reply.text }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
  </div>
{% empty %}
  <p>No comments yet.</p>
{% endfor %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Django Blog{% endblock %}</title>
   
    <!-- Add additional stylesheets and JavaScript files as needed -->
</head>
<body>
    <header>
        <h1><a href="{% url 'home' %}">Django Blog</a></h1>
        <!-- Add navigation menu or links here -->
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'login' %}">Login</a></li>
                <li><a href="{% url 'register' %}">Register</a></li>
                <li><a href="{% url 'create_post' %}">create</a></li>

            {% endif %}
                <!-- Add more navigation links -->
            </ul>

            </ul>
        </nav>
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>

    <footer>
        <!-- Add footer content here -->
        &copy; {{ year }} Django Blog
    </footer>
</body>
</html>

blog/templates/blog/category_list.html
{% extends "blog/base.html" %}

{% block content %}

  <h1>Blog Posts by Category: {{ category.name }}</h1>

  <ul>

    {% for post in category.posts.all %}

      <li>
        <a href="{% url 'post_detail' post.id %}">{{ post.title }}</a>
      </li>
    {% empty %}

      <li>No posts in this category.</li>

    {% endfor %}

  </ul>
  
{% endblock %}

blog/templates/blog/create_post.html
{% extends "blog/base.html" %}

{% block content %}
  <h1>Create a New Blog Post</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <label for="categories">Categories:</label>
    <!-- <select name="categories" id="categories">
        {% for category in categories %}
            <option value="{{ category.id }}">{{ category.name }}</option>
        {% endfor %}
    </select>
    <label for="tags">Tags:</label>
    <select name="tags" id="tags" multiple>
        {% for tag in tags %}
            <option value="{{ tag.id }}">{{ tag.name }}</option>
        {% endfor %}
    </select> -->
    <input type="submit" class="btn btn-primary" value="Create">
    
  </form>
{% endblock %}

blog/templates/blog/login.html
{% extends "blog/base.html" %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" required><br>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password" required><br>
    <input type="submit" value="Login">  </form>
  <p>Don't have an account? <a href="{% url 'register' %}">Register here</a></p>
{% endblock %}

blog/templates/blog/logout.html
{% extends "base.html" %}

{% block content %}
  <h2>Logout</h2>
  <p>Are you sure you want to log out?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Logout</button>
  </form>
{% endblock %}

blog/templates/blog/post_delete.html
{% extends "blog/base.html" %}

{% block content %}
<h2>Delete Post</h2>
<p>Are you sure you want to delete "{{ object.title }}"?</p>

<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'post_detail' post_id=object.id %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}
  <article>
    <h1>{{ post.title }}</h1>
    <p>Published on {{ post.publication_date|date:"F j, Y" }} by {{ post.author }} | Updated: {{ post.updated_date }}</p>
    <div class="content">
      {{ post.content|safe }}
    </div>
  </article>
  <a href="{% url 'post_delete' pk=post.id %}" class="btn btn-danger">Delete</a>
  <a href="{% url 'post_update' pk=post.id %}" class="btn btn-primary">Edit</a>

  <p>Category: {{ post.category }}</p>
  <p>Tags: 
      {% for tag in post.tags.all %}
          <a href="{% url 'tag_detail' tag.name %}">{{ tag.name }}</a>{% if not forloop.last %}, {% endif %}
      {% endfor %}
  </p>
  
  <h3>Comments</h3>
  {% for comment in comments %}
    <div class="comment">
        <p>{{ comment.text }}</p>
        <p>Posted by: {{ comment.author }}</p>
        <h3>Reply to Comment</h3>
        <form method="post">
            {% csrf_token %}
            {{ comment_form.text }}
            <input type="hidden" name="parent_comment" value="{{ parent_comment.id }}">
            <button type="submit">Reply</button>
        </form>

        <div class="replies">
          {% for reply in parent_comment.commentreply_set.all%}
              <div class="comment">
                  <p>{{ reply.text }}</p>
                  <p>Posted by: {{ reply.author }}</p>
                  <!-- Reply form for this reply (if needed) -->
              </div>
          {% endfor %}
      </div>

    </div>
{% empty %}
    <p>No comments yet.</p>
{% endfor %}

<form method="post">
  {% csrf_token %}
  {{ comment_form.as_p }}
  <button type="submit">Submit</button>
</form>
  
{% endblock content %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}

{% block content %}
  <h2>{% if not post.id %}Create New Post{% else %}Edit Post{% endif %}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Submit">
  </form>
  <a href="{% url 'post_list' %}" class="btn btn-secondary">Cancel</a>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block content %}
<h1>Blog Posts</h1>
<ul>
    {% for post in posts %}
        <li><a href="{% url 'post_detail' post.id %}">{{ post.title }}</a></li>

        {% empty %}
            <li>No products available</li>
    {% endfor %}

    <p>Categories:
        {% for category in categories %}
            <a href="{% url 'category_list' category.id %}">{{ category.name }}</a>
            {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>
    
    <p>Tags:
        {% for tag in tags %}
            <a href="{% url 'tag_list' tag.id %}">{{ tag.name }}</a>
            {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>
    

</ul>
{% endblock %}

blog/templates/blog/post_update.html
{% extends "blog/base.html" %}

{% block content %}
<h2>Edit Post</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <label for="categories">Categories:</label>
    <select name="categories" id="categories">
        {% for category in categories %}
            <option value="{{ category.id }}">{{ category.name }}</option>
        {% endfor %}
    </select>
    <label for="tags">Tags:</label>
    <select name="tags" id="tags" multiple>
        {% for tag in tags %}
            <option value="{{ tag.id }}">{{ tag.name }}</option>
        {% endfor %}
    </select>
    <input type="submit" class="btn btn-primary" value="Update">
</form>
<a href="{% url 'post_detail' post_id=object.id %}" class="btn btn-secondary">Cancel</a>
{% endblock %}

blog/templates/blog/register.html
{% extends "blog/base.html" %}

{% block content %}
    <h2>Register</h2>
    <form method="post">
        {% csrf_token %}
        
        {{ form.as_p }}
        <button type="submit">Register</button>
        <!-- Your registration form fields here
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required><br>
        <label for="password1">Password:</label>
        <input type="password" id="password1" name="password1" required><br>
        <label for="password2">Confirm Password:</label>
        <input type="password" id="password2" name="password2" required><br>
        <input type="submit" value="Register"> -->

    </form>
    {% if form.errors %}
    <p>There are errors in the form. Please correct them.</p>
  {% endif %}

  {% endblock %}

blog/templates/blog/reply_to_comment.html
{% extends "base.html" %}

{% block content %}
  <h2>Reply to Comment</h2>

  <form method="post">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <button type="submit" class="btn btn-primary">Submit Reply</button>
  </form>

  <a href="{% url 'post_detail' post_id=parent_comment.post.id %}">Back to Post</a>
{% endblock %}

blog/templates/blog/tag_list.html
{% extends "blog/base.html" %}

{% block content %}

  <h1>Blog Posts by Tag: {{ tag.name }}</h1>

  <ul>

    {% for post in tag.posts.all %}

      <li>
        <a href="{% url 'post_detail' post.id %}">{{ post.title }}</a>
      </li>

    {% empty %}

      <li>No posts with this tag.</li>

    {% endfor %}

  </ul>
  
{% endblock %}